language: rust

rust:
    - nightly

matrix:
  include:
    - language: rust
      rust: nightly
      name: "check wasm32 support"
      install: rustup target add wasm32-unknown-unknown
      script: cargo check --target wasm32-unknown-unknown

script:
    - cd hanzi_lookup
    - cargo build --target wasm32-unknown-unknown --release
    - cargo test
